feat: payggy in group chat
logos-innovation-lab/waku-objects-playground pull request #290
Opened 2023-08-09 18:39 UTC by vojtechsimetka

Implements #269

2023-08-10 12:48 UTC, agazso commented on src/lib/objects/payggy/views/selectUser.svelte
> +	<InputField bind:value={filterText} placeholder="Search froup members..." />
```suggestion
	<InputField bind:value={filterText} placeholder="Search group members..." />
```

2023-08-10 12:51 UTC, agazso commented on src/lib/objects/payggy/views/selectUser.svelte
> +<script lang="ts">
In other files the naming convention is to use dashes as separator between words. According to that this file should be called `select-user.svelte` and not `selectUser.svelte`

2023-08-10 13:31 UTC, agazso requested changes
One issue I see with this is that the texts on the widget and the detail view mentions 'You received...' even if I was not part of the transaction.

For example, `a` makes a transaction to `b` and I see it as `c`, will look like as if `c` received the transaction.

2023-08-11 14:04 UTC, vojtechsimetka commented
@agazso thanks for reporting it, I did not realize. It's implemented now :)

![Screenshot 2023-08-11 at 15 31 18](https://github.com/logos-innovation-lab/waku-objects-playground/assets/7974813/f9fe2446-2aa7-4ca0-907b-84a6e156820d)

![Screenshot 2023-08-11 at 16 03 49](https://github.com/logos-innovation-lab/waku-objects-playground/assets/7974813/98160bce-66b4-47f9-98b0-a05d986147fe)

2023-08-11 14:17 UTC, sugarpusher commented
I found an issue, the recipient's Payggy bubble shows the sender as the wrong person

2023-08-11 16:01 UTC, agazso approved these changes

2023-08-11 16:40 UTC, merged